password=input("What is thee password?")
if password == "dragon":
    print("There was once a happy dragon who lived in the forest.")
    print("He loved to play games with his dad.")
    print("There was no one that could hurt them.")
    print("One day, his father got killed in a gang fight.")
    print("He became depressed.")
    print("To help him cope with his depression, he started drinking.")
    print("He developed a serious drinking problem.")
    print("The dragon died of alcohol overdose and all of the villager imprisoned in his dungeon were free to escape.")
